### ISSUE TITLE
FileChannel compress fails leaving empty .gz files

### ISSUE THREAD

**Issue by gottafixthat** [pocoproject/poco#865] opened 2015-06-18 22:38 UTC
I have several applications that are all coded identically with regard to log files, but one of them is not able to compress its rotated logs correctly.  All of the others compress and rotate logs correctly.

The only difference is that the program that is not rotating its logs correctly is very busy, and is logging hundreds of lines per minute.  That also makes its log files much larger.

I've gone through the RotateStrategy code and the FileChannel code and have found nothing obvious.

Here is how the loggers are setup:

``` c++
AutoPtr <ConsoleChannel> pCons(new ConsoleChannel);
AutoPtr <FileChannel> pChannel(new FileChannel);
AutoPtr <PatternFormatter> pPF(new PatternFormatter);
pChannel->setProperty("path",   "/var/log/program.log");
pChannel->setProperty("rotation", "23:59");
pChannel->setProperty("archive", "timestamp");
pChannel->setProperty("purgeAge", "30 days");
pChannel->setProperty("times", "local");
pChannel->setProperty("compress", "true");
pPF->setProperty("times", "local");
pPF->setProperty("pattern", "%Y-%m-%d %H:%M:%S.%i %q:%s %t");
AutoPtr <FormattingChannel> pFC(new FormattingChannel(pPF, pChannel));
AutoPtr <FormattingChannel> pCC(new FormattingChannel(pPF, pCons));
AutoPtr <SplitterChannel> pSplitter(new SplitterChannel);
pSplitter->addChannel(pFC);

if (!config().getBool("application.runAsDaemon", false)) {
    pSplitter->addChannel(pCC);
}

Logger::root().setChannel(pSplitter);
Logger::root().setLevel("information");
```

As I said, I have 5 different programs all setup identically using this, with the only difference being the "path" property.  4 of the 5 rotate their logs correctly, the 5th leaves the directory looking like this:

```
-rw-rw-rw- 1 root root  3421175 Jun 18 15:37 csxmlsrv.log
...
-rw-rw-rw- 1 root root 17495949 Jun 16 23:58 csxmlsrv.log.20150616235908377
-rw-rw-rw- 1 root root        0 Jun 16 23:59 csxmlsrv.log.20150616235908377.gz
-rw-rw-rw- 1 root root  5884837 Jun 17 23:58 csxmlsrv.log.20150617235903412
-rw-rw-rw- 1 root root        0 Jun 17 23:59 csxmlsrv.log.20150617235903412.gz
```

**Comment by aleks-f** [comment] 2015-06-23 18:30
The problem is in [ArchiveStrategy::moveFile](https://github.com/pocoproject/poco/blob/develop/Foundation/src/ArchiveStrategy.cpp#L121); since [ArchiveCompressor::compress](https://github.com/pocoproject/poco/blob/develop/Foundation/src/ArchiveStrategy.cpp#L50) is an active method executed in a separate thread, an exception thrown there will terminate the thread.

We should at least wrap [ArchiveCompressor::compressImpl()](https://github.com/pocoproject/poco/blob/develop/Foundation/src/ArchiveStrategy.cpp#L53-L72) in try/catch and make sure it is transactional (either succeeds entirely or does nothing).

**Comment by jparke** [comment] 2016-12-10 20:12
I am having the same problem. Has anyone found a fix for this, or have any idea how to fix?

**Comment by obiltschnig** [comment] 2016-12-29 13:17
For 1.7.7, I have added some error handling to leave the uncompressed file there and remove the compressed file if compressing the file fails for some reason. Have not been able to reproduce the issue, though.

**Comment by jparke** [comment] 2016-12-29 13:56
Thanks for the fix. I'll give it a try.

**Comment by obiltschnig** [comment] 2016-12-29 14:01
In case this happens reproducibly, try printing the exception happening in ArchiveCompressor::compressImpl() to cout and see what it is.

**Comment by jparke** [comment] 2016-12-29 14:07
I will definitely do so.

**Closed** 2019-04-28 12:09 UTC
Labels: bug
