### ISSUE TITLE
Lost WebSocket Frames after Client Websocket Handshake is complete

### ISSUE THREAD

**Issue by dereszet** [pocoproject/poco#1212] opened 2016-03-23 12:49 UTC
WebSocket frames may get lost when a client side WebSocket establishes a connection and the server sends the first WebSocket frames immediately after sending the Opening Handshake.
The client side websocket reads and parses the HTTP response before detaching the socket from the HTTPClientSession to be passed to the WebSocket. If, at the time of reading the HTTP Response from the server, a WebSocket Frame has already been sent (and is available in the client side TCP buffer), the HTTPInputStream will receive data from the socket beyond the end of the HTTP response (due to a buffer size of 4096 bytes). This data will consequently not be available to the WebSocket once the WebSocket is established.

This bug requires every server to wait a short time before sending data after completing the WebSocket handshake.

**Comment by harishparasuram** [comment] 2017-01-04 15:15
I am also facing this issue. Is there any update on the fix (or) any workaround?

**Comment by harishparasuram** [comment] 2017-01-09 06:00
Hi @obiltschnig , is there any update on this issue or could you please suggest any workaround (only on client side) to avoid this issue.

Any update would be appreciated.

Thanks.

**Comment by obiltschnig** [comment] 2017-01-09 18:42
Unfortunately there is no easy fix for this on the client. A workaround on the server side is to wait a couple of milliseconds after the WebSocket handshake before sending the first frame.

**Closed** 2017-02-20 17:17 UTC
Labels: bug, fixed

**Comment by AndrewVorobey** [comment] 2017-06-30 11:47
This fix doesn't work. 
If network is unstable, this bug appears frequently.  In this case delay after handshake on server is helpful, but not always. (delay is 100 ms)

**Comment by harishparasuram** [comment] 2017-10-26 09:58
Hi @obiltschnig ,
I am using POCO 1.7.8 which has this fix.

Now if the first WebSocket frame is received with HTTP response, I am able to read that frame with "receiveFrame" method. 

But with the same case, if I call "poll" with "Poco::Net::Socket::SELECT_READ" mode before "receiveFrame", poll returns false after my timeout. (It seems poll is not considering the data in the _buffer.) 

Please do let me know if I am missing something.

**Comment by harishparasuram** [comment] 2017-11-07 11:51
Hi @obiltschnig , Is there any update on this issue? Thanks.

**Comment by obiltschnig** [comment] 2017-11-07 12:10
Fix will be in 1.8. Will require you to call `available()` before `poll()` to check for any bytes already in the buffer.

For this, you must change `WebSocketImpl::available()` to:

```c++
int WebSocketImpl::available()
{
    int n = _buffer.size() - _bufferOffset;
    if (n > 0)
        return n;
    else
        return _pStreamSocketImpl->available();
}
```

**Comment by harishparasuram** [comment] 2017-11-08 07:44
Hi @obiltschnig ,
Thanks for the quick response.

Since the fix is handled in "available" method,

1. We'll not be able to use "poll" to determine, whether the successive "receiveFrame" would block. Is this the expected behavior?
2. Also, "available" will not give a clear information whether the successive "receiveFrame" would block (if the buffer contains an incomplete WS frame).

So is there any API available in the library, to check whether the successive "receiveFrame" would block?

Please do let me know if I am missing something.

**Comment by obiltschnig** [comment] 2017-11-08 07:48
You'll have to call both available() and poll(). E.g., call available() first and if it returns 0, call poll().

```
if (ws.available() || ws.poll(...)) ...
```

There is no API available to determine whether a complete frame can be read without blocking.
