### ISSUE TITLE
no member named 'snprintf' in the global namespace

### ISSUE THREAD

**Issue by Heather** [pocoproject/poco#1045] opened 2015-11-26 08:16 UTC
building on FreeBSD fails with 

``` shell
[  0%] Building CXX object Foundation/CMakeFiles/Foundation.dir/src/AbstractObserver.cpp.o
In file included from /home/heather/A/SB/MITK-superbuild/ep/src/Poco/Foundation/src/AbstractObserver.cpp:17:
In file included from /home/heather/A/SB/MITK-superbuild/ep/src/Poco/Foundation/include/Poco/AbstractObserver.h:23:
In file included from /home/heather/A/SB/MITK-superbuild/ep/src/Poco/Foundation/include/Poco/Foundation.h:148:
In file included from /home/heather/A/SB/MITK-superbuild/ep/src/Poco/Foundation/include/Poco/Bugcheck.h:24:
In file included from /usr/include/c++/v1/string:437:
/usr/include/c++/v1/cstdio:143:9: error: no member named 'snprintf' in the global namespace
using ::snprintf;
      ~~^
/usr/include/c++/v1/cstdio:148:9: error: no member named 'vfscanf' in the global namespace; did you mean 'fscanf'?
using ::vfscanf;
```

any suggestions around this?

also can't use PocoConfig.cmake from BSD: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=204824
support with this issue will be very welcome

**Comment by aleks-f** [comment] 2015-11-30 03:48
I can't reproduce this compile error with bare gmake build (Foundation and testsuite build without a problem) and cmake is throwing fits, I'm not very familiar with it; assigning to cmake maintainer. /cc @bachp

**Comment by Heather** [comment] 2015-11-30 04:37
@aleks-f I used clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512

**Comment by aleks-f** [comment] 2015-11-30 05:19
Still can't reproduce:
> $ uname -a
FreeBSD freebsd10 10.2-RELEASE FreeBSD 10.2-RELEASE #0 r286666: Wed Aug 12 15:26:37 UTC 2015     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
> $ clang++ --version
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
Target: x86_64-unknown-freebsd10.2
Thread model: posix`

**Comment by aleks-f** [comment] 2015-11-30 05:52
Since it seems fails in `<string>` header, it either wants some other include before it or it's a clang bug. What version of poco are you using?

**Comment by Heather** [comment] 2015-11-30 07:44
@aleks-f was trying 1.6.0 and master

**Comment by Heather** [comment] 2015-11-30 10:52
@aleks-f build log: https://gist.github.com/Heather/568fb047e69da28daf48
cmake cache: https://gist.github.com/Heather/5f6de48c1e1baf676d35

**Comment by aleks-f** [comment] 2015-11-30 18:31
I suspect it may be picking up libstdc++. To narrow it down, try to build Foundation with gmake only:

```
git clone https://github.com/pocoproject/poco
cd poco
export POCO_BASE=`pwd`
./configure
cd Foundation
gmake
```

This will build with g++. To change to clang, modify the [config](https://github.com/pocoproject/poco/blob/develop/build/config/FreeBSD#L18). You can also experiment with CXXFLAGS, e.g.:

```CXXFLAGS        = -std=c++11 -stdlib=libc++```

**Comment by rakuco** [comment] 2016-01-06 16:14
The build log doesn't show the full command line being passed. In general, the absence of functions such as `snprintf` indicate you are building with non-standard values for the visibility macros (e.g. `__ISO_C_VISIBLE` or `_POSIX_C_SOURCE`).

**Closed** 2016-02-27 16:18 UTC
Labels: question

**Comment by tt83** [comment] 2016-09-09 17:46
This is same issue as here: https://git.reviewboard.kde.org/r/119696/
