### ISSUE TITLE
Compress with nonseekable

### ISSUE THREAD

**Issue by s0li** [pocoproject/poco#335] opened 2013-11-26 14:33 UTC
When I try to create a zip file and set seekableOut argument of Compress ctor to false the result file is corrupted. 

Poco::Zip::Compress c(out, false); /* seekableOut = false */
...
compressor.addFile(anEntry, anEntry); /* Compression level = MAX, Compression Algorithm = DEFLATE */

Looking at the resulting zip file in hex-editor I can see the following things that are wrong:
1. general purpose bit flag in Central directory is invalid - it should be [0A 00], instead it is  [00 02]

2. crc, compressed size, uncompressed size in central directory are all zeros.

3. For one of the files in the zip file (I compressed two files) the local header offset in the central directory was invalid.

4. central directory offset is invalid.

**Comment by Popovich** [comment] 2015-01-22 17:17
When it will be fixed????

**Comment by martin-osborne** [comment] 2015-02-28 10:01
I have a potential fix for this issue in my issue_335 branch.

Before the proposed change, archives created for non-seekable streams would not decompress with minizip, now they will, and I've added a regression test for this.

I manually checked that after the proposed change the generated archives look correct.  Specifically that the archives created for non-seekable streams have non-zero data descriptor fields and the offset to the start of the central directory is correct.  I would like to add a test to ensure the archives are now fit for purpose, but I am struggling to do so.  

Does anyone have any suggestions as to how I might do this?  @s0li perhaps you could provide a small repro?

**Comment by martin-osborne** [comment] 2015-05-01 11:09
Status update:  Although the recent Zip 64 changes merge fairly easily, the tests I added no longer pass.  I'm not planning to spend any time investigating why, as there doesn't seem to be much interest in this issue.
However, I can confirm that the issue still seems to exists in the develop branch, in so much as, archives created for non-seekable streams can not be extracted with 7-zip.

**Comment by MrHacky** [comment] 2015-10-02 09:59
this is pretty unfortunate, as the reason i chose to use poco zip is because it claimed to be able to stream a zip file directly to the network.

Note that not only 7-zip isn't able to open the file, winrar and the windows build-in zip browser also report the zip file is corrupt.

I manually applied the 'Potential fix for Issue #335' change, and now winrar and windows succeed in unzipping the file, but 7-zip still fails.

Is there anything i can help to do to get this issue resolved?

**Comment by martin-osborne** [comment] 2015-10-04 10:57
> Is there anything i can help to do to get this issue resolved?

Not sure if this question is directed at me or not, but...  I'm probably no better qualified than you to look into this issue, I was just someone with a bit of time on my hands who wanted to contribute, and without @s0li detailed diagnosis, I probably wouldn't have attempted it.  I'll have a bit of spare time in the near future, so I might take it up again.  But let's be honest, sitting down with hexdumps and a copy of [APPNOTE.TXT](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) isn't the most fun activity in the world.  :-)

As I left it, I was a bit stuck on the question of whether or not the generated archives were not just valid, but fit for purpose.  But Issue #893 has made me wonder, was I missing something obvious.

Sorry I can't be of more help at moment.

**Comment by MrHacky** [comment] 2015-10-05 08:24
allright thanks for the reply, if i have any extra spare time this week i'll try to take a crack at it myself then.

**Comment by MrHacky** [comment] 2015-10-07 19:36
After investigating i think i have found and fixed all issues.
I started with https://github.com/martin-osborne/poco/commit/6bafe7c3c6bab0795d1a61eeabbe3d542526a70e, but the line ```_pHeader->setStartPos(_pHeader->getStartPos());``` in ZipStream.cpp also needed to be moved because of the zip64 changes. This made winrar and windows happy with the zip file created.

The change in ZipFileInfo.cpp was needed to make sure the general purpose bit flag in the central directory was set correctly to the same value as in the local file header. This made 7-zip happy as well.

**Comment by obiltschnig** [comment] 2015-10-08 08:50
Could you submit a pull request for your fixes?

**Closed** 2016-02-27 23:48 UTC
Labels: bug, fixed
