### ISSUE TITLE
1.7.8p3 building x64 fails

### ISSUE THREAD

**Issue by gmax79** [pocoproject/poco#1780] opened 2017-07-01 11:54 UTC
buildwin 140 build static_mt debug x64 
fails with error:
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found, ...
 libs\poco\Foundation\Foundation_vs140.vcxproj]

buildwin script (in 1.7.8p3) uses Foundation_vs140.vcxproj, not Foundation_x64_vs140.vcxproj
ps. 1.7.7 ok!

**Comment by Burgch** [comment] 2017-07-03 15:47
This is caused by the change in [buildwin.cmd](https://github.com/pocoproject/poco/blob/develop/buildwin.cmd) in 4f2f7c61d70847d6a30cdc4b90311aea5647edd8 to using `amd64` when calling the `vcvarsall` script. This has since been fixed in 3b56f3c73eb61b9114aedf5bc1d67a701f2a1964 which switched back to using `x86_amd64`.

**Closed** 2017-11-08 14:53 UTC
Labels: fixed
