### ISSUE TITLE
POCO does not build with OpenSSL 1.1

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#1460] opened 2016-10-18 21:20 UTC
According to some reports (e.g. on [Twitter](https://twitter.com/madhankk/status/787503560095215616)) POCO does not build with OpenSSL 1.1. Need to investigate.

**Comment by mbuckaway** [comment] 2016-10-19 15:59
Compiling Poco 1.7.6 on Windows with visual studio with Net_SSL enabled, the crypto lib fails to build with many errors (see attached) with building against openssl 1.1.0b. Some of the types in openssl 1.1 have changed and required some rework of some of our other apps. Unfortunately, this is a bit of a show stopper for us because we now are using openssl 1.1 exclusively.

[errors.txt](https://github.com/pocoproject/poco/files/539541/errors.txt)

**Comment by AnotherCodeSegment** [comment] 2016-10-20 11:48
Duplicate of #1376.

**Closed** 2016-12-07 11:45 UTC
Labels: third-party
