### ISSUE TITLE
Error when linking 32-bit on a 64-bit machine

### ISSUE THREAD

**Issue by avishaib** [pocoproject/poco#894] opened 2015-08-03 08:16 UTC
When compiling 32-bit poco on a 64-bit machine (tested on Debian 7), link fails.
1. The configure script is set with --cflags=-m32
2. OSARCH_64BITS is set to 0
3. POCO_TARGET_OSARCH is set to i386

The compiler creates 32-bit object files, but the -m32 flag is missing from the g++ command when linking the libraries.

FIX:
It can be fixed by adding -m32 to SHLIBFLAGS in build/rules/global in case OSARCH_64BITS==0.

**Comment by Tigzy** [comment] 2018-05-04 14:54
Hey there, it's 2018 and I'm still having the issue. I'm unable to link my 32 bits compiled object from a 64 bits machine. Is there a reason that isn't released in official package yet?

**Comment by Tigzy** [comment] 2018-05-04 16:40
The latest, 1.9.0 doesn't have the fix

**Comment by Tigzy** [comment] 2018-05-11 11:47
Up?

**Comment by Tigzy** [comment] 2018-05-11 12:28
using: 
`./configure --shared --cflags='-g -O0 -w -m32' --omit=Data/MySQL,Data/ODBC`
I've tried to define 
OSARCH_64BITS=0
POCO_TARGET_OSARCH='i386'
still having build errors at link time (output not compatible with i386:x86-64)

**Comment by zosrothko** [comment] 2018-05-11 12:41
Could you add the file build/config/Linux32-gcc with the content below and use the following command
`./configure --config=Linux32-gcc --shared --cflags='-g -O0 -w -m32' --omit=Data/MySQL,Data/ODBC`

```
#
# Linux
#
# Make settings for crossbuilding Poco Linux x86 on a Linux x86_64 OS.
#
#

include $(POCO_BASE)/build/config/Linux

#
# Crossbuild Settings
#
POCO_TARGET_OSNAME  = Linux
POCO_TARGET_OSARCH  = x86

#
# Compiler and Linker Flags
#
CFLAGS64        += -m32
CXXFLAGS64      += -m32
SHLIBFLAGS64    += -m32
LINKFLAGS64     += -m32
```

**Comment by Tigzy** [comment] 2018-05-11 12:58
testing, be back soon.

**Comment by zosrothko** [comment] 2018-05-11 13:25
You can add those options on the configure command
```
  --include-path=<path>
    Add search path for header files.

  --library-path=<path>
    Add search path for library files.
```

**Comment by Tigzy** [comment] 2018-05-11 13:27
Yes but these will be static. I have no way to specify both 32 and 64 bits library-paths. If I do this, I'm pretty sure it'll try to link to the wrong version of the lib.

**Comment by Tigzy** [comment] 2018-05-11 13:29
I'm not sure it's clear. Let say I have a OpenSSL folder with : 
OpenSSL/gcc/64/include
OpenSSL/gcc/64/libs
OpenSSL/gcc/32/include
OpenSSL/gcc/32/libs

If I add thoses paths (all of them) and just run the default configure, will it try to build both 32 and 64 bits?

**Comment by zosrothko** [comment] 2018-05-11 13:32
No, what you are trying to achieve if I understand correctly is crosscompiling a binary toward a 32 bit arch on a 64 bits host. Thus you should specify only the 32 bit include/libraries for OpenSSL

**Comment by Tigzy** [comment] 2018-05-11 13:38
I'm trying to build both, but it only works for 64 bits (I got it compiled fine). 
For 32 bits, it seems to be only compiling the .o but still tries to link 32 bits. Even with the fix above.

**Comment by zosrothko** [comment] 2018-05-11 13:53
You cannot build both Poco for a 32 arch and 64 arch in the same run. Thus I would suggest

1. ./configure --shared --cflags='-g -O0 -w ' --omit=Data/MySQL,Data/ODBC
2. make -s install
3. make distclean
4.  ./configure --config=Linux32-gcc --shared --cflags='-g -O0 -w ' --omit=Data/MySQL,Data/ODBC --include-path=OpenSSL/gcc/64/include --library-path=OpenSSL/gcc/64/libs
5. make -s install

**Comment by Tigzy** [comment] 2018-05-11 13:55
Yes, that's what I'm trying actually. I have a script that makes a copy of the sources folder locally, same for OpenSSL include/libs, and run a separate configure for 32 , 64 debug / release (4 times then).  I'll give it a second try and get error log if that can help

**Comment by Tigzy** [comment] 2018-05-11 14:10
Ok, looks like when I run the /usr/bin/ld command with "/usr/bin/ld -m elf_i386" manually it works. 
So whatever the build script is doing, it's missing -m elf_i386

**Comment by Tigzy** [comment] 2018-05-11 14:44
that broken ld command is because the g++ command is wrong as well: 
g++ *-m32* -shared -Wl,-soname,libPocoFoundationd.so.31 -o [...]

**Comment by Tigzy** [comment] 2018-05-11 14:45
So the question is, how do I fix the G++ command inside the build scripts?

**Comment by Tigzy** [comment] 2018-05-11 15:11
With this it seems to be compiling now: 
I think only CXXFLAGS is needed, to be confirmed

#
# Compiler and Linker Flags
#
CFLAGS          += -m32
CXXFLAGS        += -m32
CFLAGS32        += -m32
CXXFLAGS632     += -m32
SHLIBFLAGS32    += -m32
LINKFLAGS32     += -m32
CFLAGS64        += -m32
CXXFLAGS64      += -m32
SHLIBFLAGS64    += -m32
LINKFLAGS64     += -m32

**Comment by zosrothko** [comment] 2018-05-12 10:52
Can you push on Google Drive or WeTransfer or whatever, your openssl libs and includes both for 32 & 64 arch?

**Comment by Tigzy** [comment] 2018-05-14 07:51
I think that's ok, it compiled fine with the modification above.

**Comment by klaprade** [comment] 2019-03-13 17:45
I got link errors when building 32-bit POCO on a 64-bit Linux machine.  My fix is to add "$(LINKFLAGS)" to the "SHLIB" definition in "build/config/Linux".  With that change, building 64-bit or 32-bit works flawlessly.

I built 32-bit POCO on RHEL6.6 with GCC 4.4.7 thus:
`$ ../configure --shared --unbundled=zlib,expat --typical --omit=Data --no-samples --prefix=$PWD --cflags="-m32 -msse2 -mfpmath=sse -march=pentium4"`

Here is my change for POCO 1.9.0:
--------
```
--- ./build/config/Linux-orig	2018-03-08 09:28:41.000000000 -0500
+++ ./build/config/Linux	2019-02-27 14:37:50.566953000 -0500
@@ -18,7 +18,7 @@
 LINK    = $(CXX)
 LIB     = ${CROSS_COMPILE}ar -cr
 RANLIB  = ${CROSS_COMPILE}ranlib
-SHLIB   = $(CXX) -shared -Wl,-soname,$(notdir $@) -o $@
+SHLIB   = $(CXX) $(LINKFLAGS) -shared -Wl,-soname,$(notdir $@) -o $@
 SHLIBLN = $(POCO_BASE)/build/script/shlibln
 STRIP   = ${CROSS_COMPILE}strip
 DEP     = $(POCO_BASE)/build/script/makedepend.gcc 
```
--------

**Closed** 2019-04-28 12:09 UTC
