### ISSUE TITLE
poco-1.9.0-release broken since push of 0c6d16ec85f80ea3ce05a8f2ff52c1b3ba240a41 on https://github.com/pocoproject/openssl

### ISSUE THREAD

**Issue by sebastianstolzenberg** [pocoproject/poco#2290] opened 2018-04-13 09:58 UTC
Note: checking out 'poco-1.9.0-release'.
  
  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by performing another checkout.
  
  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -b with the checkout command again. Example:
  
    git checkout -b <new-branch-name>
  
  HEAD is now at 9496678... update openssl module branch
  Submodule 'gradle' (https://github.com/pocoproject/gradle) registered for path 'gradle'
  Submodule 'openssl' (https://github.com/pocoproject/openssl) registered for path 'openssl'
  Cloning into 'gradle'...
  Submodule path 'gradle': checked out '73b60316d69e239902711f32dca95f6d97aa257c'
  Cloning into 'openssl'...
  fatal: reference is not a tree: 26b1673caad94a702b6d694f48f917a283b30777
  Unable to checkout '26b1673caad94a702b6d694f48f917a283b30777' in submodule path 'openssl'
  CMake Error at pocoproject-prefix/tmp/pocoproject-gitclone.cmake:83 (message):

**Comment by aleks-f** [comment] 2018-04-13 14:35
yeah, gimme a bit, I'll get to it. the problem is that we keep binaries in that repo and it has to be purged occasionally or else it grows too much in size. Although I am able to shrink it locally, I'm not quite sure what exactly github does, because links to commits from eg. issues still work ...

**Comment by andyli** [comment] 2018-04-17 05:13
We added poco as a submodule in our project, and our CI will do the recursive submodule init, which fails now. We've just upgraded poco to 1.9.0 just to avoid this issue.

**Comment by aleks-f** [comment] 2018-04-17 14:48
> it prevents cloning poco with --recursive regardless of platform as I mentioned in the previous comment.

true, but on other platforms openssl is not needed and everything will work without it. also, there is a workaround - do not check out recursively and add separate clone of openssl and gradle (if you need either) in poco directory

**Comment by franiu** [comment] 2018-04-17 18:26
Yup, broken CI on our project as well, using 1.9.1 :-(

One reason using the `--recursive` option is not the perfect solution is that we have lots of submodules and a lot of them with their own dependencies. Making exceptions would complicate the process quite a bit...

Don't mean to heckle BTW, you guys are doing great job with the Poco library!

Looking forward to the proper fix, happy to help if possible!

**Comment by zosrothko** [comment] 2018-04-17 19:02
@franiu fixed with 534c6380887e993939c11f6a2a3af96a1cb54067

**Comment by franiu** [comment] 2018-04-17 19:07
@zosrothko Awesome, thanks 👍

**Comment by aleks-f** [comment] 2018-04-17 19:09
@zosrothko I'm still seeing it fail:
```
$ git clone --recurse-submodules https://github.com/pocoproject/poco
...
Cloning into 'openssl'...
remote: Counting objects: 221, done.
remote: Total 221 (delta 0), reused 0 (delta 0), pack-reused 221
Receiving objects: 100% (221/221), 38.37 MiB | 3.94 MiB/s, done.
Resolving deltas: 100% (68/68), done.
Checking connectivity... done.
fatal: reference is not a tree: 81a16d459e05794e685be9cf97af3b01c908f992
Unable to checkout '81a16d459e05794e685be9cf97af3b01c908f992' in submodule path 'openssl'
```

**Comment by zosrothko** [comment] 2018-04-17 19:12
@aleks-f fixed for poco-1.9.1

**Comment by aleks-f** [comment] 2018-04-17 19:13
ah, ok, thanks

**Comment by aleks-f** [comment] 2018-04-17 19:16
just for the record: @zosrothko is fixing what I broke (with good intent of reducing the repo size, but not at all thinking about tags at the time) - not a good idea to keep binaries in git to start with, so just a word of warning: openssl repo is likely to go away in the future

**Comment by aleks-f** [comment] 2018-04-17 20:05
@sebastianstolzenberg this has been fixed, please check if it works for you and close the issue

**Closed** 2019-04-28 12:32 UTC
Labels: development, fixed
