### ISSUE TITLE
v1.12.0 and v1.12.1 Poco::Any compile problem

### ISSUE THREAD

**Issue by sleikang** [pocoproject/poco#3692] opened 2022-07-18 09:22 UTC
Poco\include\Poco\Any.h(124,1): fatal error C1001: 内部编译器错误。
1>C:\Dll\Poco\include\Poco\Any.h(210): message : 查看对正在编译的 类 模板 实例化“Poco::Placeholder<PlaceholderT,SizeV>”的引用
1>“D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\CL.exe”中的内部编译器错误
![image](https://user-images.githubusercontent.com/23020770/179482020-9e6fc787-0e93-43d0-bf7e-00dcfe0bc82b.png)

**Comment by aleks-f** [comment] 2022-07-18 10:10
Sorry, but we do not understand. Please use English.

**Comment by aleks-f** [comment] 2022-07-18 10:11
https://github.com/pocoproject/poco/issues/3682
https://github.com/pocoproject/poco/issues/3683

**Comment by aleks-f** [comment] 2022-07-18 10:13
https://developercommunity.visualstudio.com/t/fatal-error-C1001:-Internal-compiler-err/10095155?space=62&q=djc3ho&entry=problem&sort=newest

**Comment by sleikang** [comment] 2022-07-19 00:54
@aleks-f There is no problem with versions below 1.11.3. Versions above 1.12.0 will cause internal errors when compiling in Windows Visual Studio from the Poco/ any.h header file

**Comment by sleikang** [comment] 2022-07-19 00:54
@aleks-f There is no problem with versions below 1.11.3. Versions above 1.12.0 will cause internal errors when compiling in Windows Visual Studio from the Poco/ any.h header file

**Comment by SvenRoederer** [comment] 2022-08-11 20:53
This is a duplicate of #3728 which was merged with reference to https://github.com/pocoproject/poco/commit/8fdc04d652708fcc44bd81e351a3d9a4a0353766 for 1.12.2 milestone.
But as this change somehow was missed to be bundled for the release, I suggest to flag here for v1.12.3 milestone and have it fixed then.

**Comment by SvenRoederer** [comment] 2022-08-23 09:28
As the fix has been merged, this issue can be closed, right?
But change needs to go to master too, but this seems to be planned via branch "Fix/posix sleep" (#3705).

**Closed** 2022-10-24 07:42 UTC
Labels: fixed
