### ISSUE TITLE
uclibc support

### ISSUE THREAD

**Issue by yegorich** [pocoproject/poco#2236] opened 2018-03-20 12:07 UTC
Current version for example 1.8.1 has following configure options like `--no-fpenvironment` and `--no-wstring`, that disable some components like `wstring`. In the development branch and CMake these options are missing. But even with these options introduced there is still a problem with `wstring`.

In `Foundation/src/UnicodeConverter.cpp` file, if `POCO_NO_WSTRING` is defined, there is no UnicodeConverter class, but some other classes like VarHolder just use UnicodeConverter without checking the `POCO_NO_WSTRING` define.

What would be the best solution? A uclibc based test configuration for travis would be also useful.

**Comment by aleks-f** [comment] 2018-03-20 15:20
> In the development branch and CMake these options are missing

send pull for configure, see with @Bjoe about cmake

> What would be the best solution?

Obviously, a pull request fixing the issues :)

> A uclibc based test configuration for travis would be also useful.

see with @zosrothko

**Comment by zosrothko** [comment] 2018-03-20 15:36
This package is not supported on [Ubuntu ](https://launchpad.net/ubuntu/+source/uclibc)

**Comment by yegorich** [comment] 2018-03-21 07:18
@aleks-f, @zosrothko on the second thought we don't need uclibc based test but just a test with --no-fpenvironment and --no-wstring options given.

Pull request for for CMake options is on the way and I'll take a look at VarHolder.

**Comment by yegorich** [comment] 2018-04-19 07:51
@aleks-f I've looked at VarHolder and found your commit (1aa28e1491ec4ac26882ed78f600e188295a9c64) adding Unicode support to this class. Could you then take care of adding `POCO_NO_WSTRING` to it? Thanks.

**Comment by Bjoe** [comment] 2018-04-23 13:37
For the info: `POCO_NO_WSTRING` is added in cmake build system and merged into `develop` branch. See cmake: add missing options #2238 

@aleks-f The problem is, VarHolder don't care about define of `POCO_NO_WSTRING`. 
<pre>
FAILED: Foundation/CMakeFiles/Foundation.dir/src/VarHolder.cpp.o 
/usr/bin/clang++-5.0  -DFoundation_EXPORTS -DHAVE_PTHREAD_SETAFFINITY_NP -DHAVE_THREE_PARAM_SCHED_SETAFFINITY -DPCRE_STATIC -DPOCO_HAVE_FD_EPOLL -DPOCO_NO_WSTRING -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_REENTRANT -D_THREAD_SAFE -D_XOPEN_SOURCE=500 -Ipoco/Foundation/include -Ipoco/Foundation/src -g -D_DEBUG -fPIC   -std=gnu++14 -MD -MT Foundation/CMakeFiles/Foundation.dir/src/VarHolder.cpp.o -MF Foundation/CMakeFiles/Foundation.dir/src/VarHolder.cpp.o.d -o Foundation/CMakeFiles/Foundation.dir/src/VarHolder.cpp.o -c poco/Foundation/src/VarHolder.cpp
In file included from poco/Foundation/src/VarHolder.cpp:15:
poco/Foundation/include/Poco/Dynamic/VarHolder.h:802:9: error: no member named 'UnicodeConverter' in namespace 'Poco'
                Poco::UnicodeConverter::convert(str, val);
                ~~~~~~^
poco/Foundation/include/Poco/Dynamic/VarHolder.h:946:9: error: no member named 'UnicodeConverter' in namespace 'Poco'
                Poco::UnicodeConverter::convert(str, val);
                ~~~~~~^
poco/Foundation/include/Poco/Dynamic/VarHolder.h:2524:9: error: no member named 'UnicodeConverter' in namespace 'Poco'
                Poco::UnicodeConverter::convert(_val, val);
                ~~~~~~^
poco/Foundation/include/Poco/Dynamic/VarHolder.h:2601:47: error: no member named 'UnicodeConverter' in namespace 'Poco'
        VarHolderImpl(const char* pVal) : _val(Poco::UnicodeConverter::to<UTF16String>(pVal))
                                               ~~~~~~^
poco/Foundation/include/Poco/Dynamic/VarHolder.h:2601:68: error: unexpected type name 'UTF16String': expected expression
        VarHolderImpl(const char* pVal) : _val(Poco::UnicodeConverter::to<UTF16String>(pVal))
                                                                          ^
poco/Foundation/include/Poco/Dynamic/VarHolder.h:2670:3: error: use of undeclared identifier 'UnicodeConverter'
                UnicodeConverter::convert(_val, str);
                ^
poco/Foundation/include/Poco/Dynamic/VarHolder.h:2693:4: error: use of undeclared identifier 'UnicodeConverter'
                        UnicodeConverter::convert(_val, s);
                        ^
poco/Foundation/include/Poco/Dynamic/VarHolder.h:2705:3: error: use of undeclared identifier 'UnicodeConverter'
                UnicodeConverter::convert(_val, val);
                ^
poco/Foundation/include/Poco/Dynamic/VarHolder.h:2777:3: error: use of undeclared identifier 'UnicodeConverter'
                UnicodeConverter::convert(_val, str);
                ^
</pre>

I also mentioned this before but I forgot to create an issue :-(
My question is:
- How is this build on the Makefile based build system?
- What is the idea about `POCO_NO_WSTRING`. Because I see following approach here: https://github.com/pocoproject/poco/blob/ce2e983a631be10dea11316c4b55331142ecee81/Foundation/src/EventLogChannel.cpp#L20 `UnicodeConverter.h` is not included when `POCO_NO_WSTRING` is set but here https://github.com/pocoproject/poco/blob/ce2e983a631be10dea11316c4b55331142ecee81/Foundation/src/EventLogChannel.cpp#L46 we call the `UnicodeConverter::toUTF8()` function

**Closed** 2020-01-28 18:21 UTC
Labels: enhancement
