### ISSUE TITLE
ElementSet should change to std::list container

### ISSUE THREAD

**Issue by putilaozu** [pocoproject/poco#775] opened 2015-04-11 04:30 UTC
In MongoDB/Element.h
typedef std::set<Element::Ptr, ElementComparator> ElementSet;
Because MongoDB $cmd use first element, so elements must not been resort.
I suggest change to this:
typedef std::list<Element::Ptr> ElementSet;

**Comment by fbraem** [comment] 2015-05-14 16:42
This issue is a duplicate of number #817 and solved by pull request #818.

**Comment by fbraem** [comment] 2015-05-20 09:38
@aleks-f can you close this issue as it is a duplicate of number #817 ?

**Closed** 2015-05-20 13:12 UTC
Labels: enhancement
