### ISSUE TITLE
TCPServerParams ::setMaxThreads limit the connection ?

### ISSUE THREAD

**Issue by sue602** [pocoproject/poco#2936] opened 2020-02-20 15:58 UTC
use this example to example the echo server , but when I limit the max thread to 4, it only create 4 EchoConnection, but I make 20 clients, what's wrong with my problem ?
pParams->setMaxThreads(4);

#include <iostream>
#include <stdio.h>
using namespace std;

#include "CmdHandler.h"
#include "Poco/Thread.h"
#include "Poco/SharedLibrary.h"
#include "Poco/Net/TCPServer.h"
#include "Poco/Net/ServerSocket.h"
#include "Poco/Net/TCPServerParams.h"
using Poco::Thread;
using Poco::SharedLibrary;
using Poco::Net::TCPServer;
using Poco::Net::ServerSocket;
using Poco::Net::TCPServerParams;
using Poco::Net::TCPServerConnectionFactory;
using Poco::Net::TCPServerConnectionFactoryImpl;
#include "Poco/Net/StreamSocket.h"
#include "Poco/Net/TCPServer.h"
using Poco::Net::StreamSocket;
using Poco::Net::TCPServerConnectionFilter;

#include "Poco/Net/StreamSocket.h"
#include "Poco/Net/TCPServerConnection.h"
using Poco::Net::StreamSocket;
using Poco::Net::TCPServerConnection;

class EchoConnection: public TCPServerConnection
	{
	public:
		EchoConnection(const StreamSocket& s): TCPServerConnection(s)
		{
		}

		void run()
		{
			StreamSocket& ss = socket();
			try
			{
				char buffer[256]={0};
				int n = ss.receiveBytes(buffer, sizeof(buffer));
				while (n > 0)
				{
					printf("s =%s \n",buffer+2);
					ss.sendBytes(buffer, n);
					memset(buffer,0,256);
					n = ss.receiveBytes(buffer, sizeof(buffer));
				}
			}
			catch (Poco::Exception& exc)
			{
				std::cerr << "EchoConnection: " << exc.displayText() << std::endl;
			}
		}
	};

	class RejectFilter: public TCPServerConnectionFilter
	{
	public:
		bool accept(const StreamSocket&)
		{
			return false;
		}
	};

int main() {
	ServerSocket svs(2222);
	TCPServerParams* pParams = new TCPServerParams;
	pParams->setMaxThreads(4);
	pParams->setMaxQueued(4000);
	pParams->setThreadIdleTime(100);
	TCPServer srv(new TCPServerConnectionFactoryImpl<EchoConnection>(), svs, pParams);
	srv.start();
	//thread for waiting
	CmdHandler cmdRunnable;
	Thread thread;
	thread.start(cmdRunnable);//start
	thread.join();//
	return 0;
}

**Comment by sue602** [comment] 2020-02-20 16:03
when I set it to pParams->setMaxThreads(1024) , it works fine , but create so many Thread ( one thread / connection ?) , it's so bad

**Comment by mikallos** [comment] 2020-02-21 07:37
This is how the authors designed the library AFAIK. If you need a different approach such as coroutines or event loop etc., you may need to use a different library like Asio or libuv. Someone can correct me if i'm wrong but i think with poco one thread per connection is the only approach at the moment.

**Comment by aleks-f** [comment] 2020-02-24 18:47
Yes, it is by design. There was an attempt for [reactive http server](https://github.com/pocoproject/poco/pull/2093). I was actually able to bring it to a working state, but it was somewhat convoluted due to the fact that the original functionality was developed as thread-per-connection model. anyway, the attempt was never merged/released.

**Closed by aleks-f** 2020-02-24 18:47 UTC
Labels: question

**Comment by sue602** [comment] 2020-02-28 03:37
thank you, @aleks-f , I will re-design my game server by PollSet and Thread strategy
